config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "My Contact Form",
      :to => "majamani007@gmail.com",
      :from => %("#{name}" <#{email}>)
    }

  end

end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def new
	@contact=Contact.new
end

def create
	@contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
    	flash.now[:error] = nil
    else
    	flash.now[:error] = 'cannot send message'
    end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :show, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts=Post.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
	end

	def new
		@post=Post.new
	end

	def create
		@post=Post.new(post_params)
		if @post.save
			redirect_to @post, notice: "article succesfully posted"
		else
			render 'new', notice: "article not posted"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post, notice: "article succesfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def set_post
		@post=Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:edit, :show, :destroy, :update]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@projects=Project.all.order('created_at desc')
	end

	def new
		@project=Project.new
	end

	def create
		@project=Project.new(project_params)
		 if @project.save
		 	redirect_to @project , notice: "successfully project created"
		 else
		 	render 'new'
		 end	
	end

	def edit

	end

	def update
		if @project.update(project_params)
		   redirect_to @project, notice:" project successfully updated"
		else
			render 'edit'
		end
	end


	def show

	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end

	def set_project
		@project=Project.friendly.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts=Post.all.limit(3).order('created_at desc')
    @projects=Project.all.limit(3).order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code,language)
		  Pygments.highlight(code, lexer: language)
		end
	end	
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis:true,
			disabled_indented_code_blocks:true,
			fenced_code_blocks:true,
			lax_spacing: true,
			strikethrough:true,
			superscript:true, 
		}
		Redcarpet::Markdown.new(renderer,options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say hello</h1>
	<div class="skinny_wrapper wrapper_padding">
		 <h1>Thank you for your message!</h1>
		 <p> I'll get back to you soon </p>
	</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say hello</h1>
	<div class="skinny_wrapper wrapper_padding">
		 <%= form_for @contact do |f| %>
		 <%= f.label :name%><br>
		 <%= f.text_field :name, required: true %>
		 <br>
		 <br>
		 <%= f.label :email%><br>
		 <%= f.email_field :email, required: true %>
		 <br>
		 <br>
		 <%= f.label :message%><br>
		 <%= f.text_area :message, as: :text %>
		 <br>
		 <br>
		 <div class="hidden">
		 	<%= f.label :nickname%><br>
		 <%= f.text_field :nickname, hint: 'leave this field' %>
		 </div>
		 <%= f.submit 'send message', class: "button" %>
      <% end %>	 
	</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maninking developer blog</title>

	   <link href="https://fonts.googleapis.com/css?family=Raleway:500,700" rel="stylesheet">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags%>
  </head>

  <body>
    <header id="main_navigation" class="clearfix">
      <%= link_to "Mani develop", root_path, class:"name"%>
			<nav>
        <%= link_to "Articles", posts_path %>
  			<%= link_to "Projects", projects_path %>
  			<%= link_to "Contact", new_contact_path %>
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% end %>
        	</nav>
		</header>
    <%if notice%>
     <p class="notice"><%= notice %></p>
    <% elsif alert %>
     <p class="alert"><%= alert %></p>
     <% end %>
    <%= yield %>

    <footer id="main_footer">
			<p class="copywright">&copy; 2017 Manikandan</p>
			<nav>
				<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-github" aria-hidden="true"></i></a>
			</nav>
		</footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
this.page.url = '<%= url_for(post_url(@post))%>';  
// Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://blogging-4.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 <% if @post.errors.any? %>
 	<h2><%=pluralize(@post.errors.count, "error")%></h2>
 	<ul>
 		<% @post.errors.full_messages.each do |name,msg|%>
 		<li><%=msg%></li>
 		<% end %>
 	</ul>
 <% end %>
	 <%= f.label :title%><br>
	 <%= f.text_field :title %>
	 <br>
	 <br>
	 <%= f.label :content%><br>
	 <%= f.text_area :content %>
	 <br>
	 <br>
	 <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit post</h1>
<div class="skinny_wrapper wrapper_padding">
	
	<%= render 'form'%>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Staff i've writen</h1>
		<div id="posts_wrapper" class="skinny_wrapper">
		<% @posts.each do |post| %>
			<div class="post">
			<p class="date"><%=post.created_at.strftime('%A, %B, %d')%></p>
			<h2><a href="#"><%= link_to post.title, post %></a></h2>
			<hr>
			</div>
		<% end %>
			
			

		</div>
		<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New post</h1>
<div class="skinny_wrapper wrapper_padding">
	
	<%= render 'form'%>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
			<header>
				<p class="date"><%= @post.created_at.strftime("%A,%B,%d")%></p>
				<h1><%= @post.title%></h1>
				<hr>
			</header>
			<div class="content">
			    <%= markdown @post.content %>
			</div>
			<% if user_signed_in? %>
				<div class="admin_links">
					<%= link_to "Edit", edit_post_path(@post) %>  
	 				<%= link_to "Delete",post_path(@post), method: :delete, date: {confirm: "Are you sure"}  %> 
				</div>
			<% end %>
			<hr>
			<div id="share_box">
				<p>Share the do list</p>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>
			</div>
			<hr>
			<%= render 'disqus'%>

			<br>
			
		</div>
		
		

 

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
 <% if @project.errors.any? %>
 	<h2><%=pluralize(@project.errors.count, "error")%></h2>
 	<ul>
 		<% @project.errors.full_messages.each do |name,msg|%>
 		<li><%=msg%></li>
 		<% end %>
 	</ul>
 <% end %>
 
	 <%= f.label :title%><br>
	 <%= f.text_field :title %>
	 <br>
	 
	 <%= f.label :description %><br>
	 <%= f.text_area :description %>
	 <br>
	 
	 <%= f.label :link%><br>
	 <%= f.text_field :link %>
	 <br>
	 
	 <%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit post</h1>
<div class="skinny_wrapper wrapper_padding">
	
	<%= render 'form'%>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Staff i've writen</h1>
		<div id="posts_wrapper" class="skinny_wrapper">
		<% @projects.each do |project| %>
			<div class="post">
			<p class="date"><%=project.created_at.strftime('%A, %B, %d')%></p>
			<h2><a href="#"><%= link_to project.title, project %></a></h2>
			<hr>
			</div>
		<% end %>
			
			

		</div>

app/views/projects/new.html.erb
<h1 id="page_title">New post</h1>
<div class="skinny_wrapper wrapper_padding">
	
	<%= render 'form'%>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime("%A,%B,%d")%></p>
		<h1><%= @project.title %></h1>
		<hr>
	</header>
	<div class="content">
	 <%= markdown @project.description %>
	 <div class="button_wrapper">
	     <a href="<%= @project.link %>" class="project_button" target="_blank">visit <%= @project.title%></a>
	  </div>
	</div>
	<br>
	<br>
	<% if user_signed_in? %>
		<div class="admin_links">
			<%= link_to "Edit", edit_project_path(@project) %>  
				<%= link_to "Delete",project_path(@project), method: :delete, date: {confirm: "Are you sure"}  %> 
		</div>
	<% end %>
	<hr>
</div>			

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix" >
			<div class="col-1 about homepage_content">
				<h2>About</h2>
				<hr>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s <a href="#">Maniking</a>.</p>
				<p>when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
			</div>
			<div class="col-2 homepage_content">
				<h2>Staff i've writen</h2>
				<hr>
		        <% @posts.each do |post| %>
						<h3><%= link_to post.title, post_path(post)%></h3>
		        <p class="date"><%= post.created_at.strftime("%A, %b, %d")%></p>
		        <% end %>
			</div>
			<div class="col-3 homepage_content">
				<h2>Staff i've articles</h2>
				<hr>
				<% @projects.each do |project|%>
					<h3><%=link_to project.title, project_path(project) %></h3>
					<p class="date"><%=project.created_at.strftime("%A, %B, %d")%></p>
				<% end %>
			</div>
</div>
		